Add Catalan translation
vixalien/sticky pull request #22
Opened 2023-03-05 20:46 UTC by gforcada

2023-03-06 07:45 UTC, vixalien requested changes
you should add the language code to `po/LINGUAS`

2023-03-06 15:03 UTC, gforcada commented
Oh right, thanks!

2023-03-06 15:04 UTC, gforcada commented
Done 😄

2023-03-07 09:24 UTC, vixalien approved these changes

2023-03-07 09:24 UTC, merged